# Generated by Django 2.2.1 on 2019-06-16 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=50)),
                ('taddress', models.CharField(max_length=50)),
                ('tcontact', models.CharField(max_length=50)),
                ('temail', models.EmailField(max_length=254)),
                ('tpassword', models.CharField(max_length=100)),
                ('tposition', models.CharField(max_length=50)),
                ('tfaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
