# Generated by Django 2.2.1 on 2019-06-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfaculty', models.CharField(max_length=50)),
                ('nbatch', models.IntegerField()),
                ('nsemester', models.IntegerField()),
                ('nnotice', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'notics',
            },
        ),
    ]
