# Generated by Django 2.2.1 on 2019-06-19 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notics',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notics',
            name='uploaded_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
