# Generated by Django 2.2.1 on 2019-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notics', '0002_auto_20190619_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notics',
            name='nsemester',
            field=models.CharField(max_length=50),
        ),
    ]
