# Generated by Django 2.2.1 on 2019-06-27 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notics', '0003_auto_20190621_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='notics',
            name='display',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notics',
            name='ntitle',
            field=models.CharField(default='Notice', max_length=50),
        ),
    ]
