# Generated by Django 2.2.1 on 2019-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notics', '0004_auto_20190627_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='notics',
            name='ntype',
            field=models.CharField(default='Others', max_length=50),
        ),
        migrations.AlterField(
            model_name='notics',
            name='nnotice',
            field=models.CharField(max_length=1000),
        ),
    ]
