# Generated by Django 2.2.1 on 2019-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='nname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
