# Generated by Django 2.2.1 on 2019-06-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_nname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='ndocument',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
