# Generated by Django 2.2.1 on 2019-05-31 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('pname', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=50)),
                ('pcontact', models.CharField(max_length=50)),
                ('pemail', models.EmailField(max_length=254)),
                ('psid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'db_table': 'parent',
            },
        ),
    ]
