# Generated by Django 2.2.1 on 2019-06-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='ppassword',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
