# Generated by Django 2.2.1 on 2019-05-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('saddress', models.CharField(max_length=50)),
                ('scontact', models.IntegerField()),
                ('semail', models.EmailField(max_length=254)),
                ('sbatch', models.IntegerField()),
                ('sfaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.Faculty')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
