# Generated by Django 2.2.1 on 2019-06-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=30)),
                ('msemester', models.CharField(max_length=50)),
                ('mexam', models.CharField(max_length=50)),
                ('msubject', models.CharField(max_length=50)),
                ('mmarks', models.IntegerField()),
                ('mbatch', models.IntegerField(default=2072)),
                ('fname', models.CharField(default='BSCCSIT', max_length=50)),
            ],
            options={
                'db_table': 'marks',
            },
        ),
    ]
