# Generated by Django 2.2 on 2019-06-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('asid', models.IntegerField()),
                ('asname', models.CharField(max_length=50)),
                ('asubject', models.CharField(max_length=50)),
                ('astatus', models.IntegerField()),
                ('adate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment_submit',
            },
        ),
    ]
