# Generated by Django 2.2.1 on 2019-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('atid', models.IntegerField()),
                ('afname', models.CharField(max_length=50)),
                ('asbatch', models.IntegerField()),
                ('aname', models.CharField(max_length=40)),
                ('asubject', models.CharField(max_length=50)),
                ('adeadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
