# Generated by Django 2.2 on 2019-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='adeadline',
            field=models.DateField(blank=''),
        ),
    ]
