# Generated by Django 2.2 on 2019-06-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20190611_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='aid',
        ),
    ]
