# Generated by Django 2.2.1 on 2019-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('attendance', models.BooleanField()),
                ('faculty', models.CharField(max_length=20)),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=3)),
                ('year', models.CharField(max_length=8)),
                ('present_days', models.IntegerField(default=30)),
                ('absent_days', models.IntegerField()),
                ('working_days', models.IntegerField()),
                ('faculty', models.CharField(max_length=20)),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
