# Generated by Django 2.2 on 2019-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.IntegerField()),
                ('std_name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('present_days', models.IntegerField(default=30)),
                ('absent_days', models.IntegerField()),
                ('working_days', models.IntegerField()),
                ('faculty', models.CharField(max_length=20)),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
